from enum import StrEnum


class AnalysisRunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    PAUSED_FOR_USER = "PAUSED_FOR_USER"
    VALIDATING = "VALIDATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AnalysisStage(StrEnum):
    MARKET_RESEARCH = "MARKET_RESEARCH"
    COMPETITOR_INTELLIGENCE = "COMPETITOR_INTELLIGENCE"
    CUSTOMER_INTELLIGENCE = "CUSTOMER_INTELLIGENCE"


class AnalysisStageStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"