"""create idea profiles table

Revision ID: 80b35165e594
Revises: 489b626beccf
Create Date: 2026-08-10 16:53:46.191363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80b35165e594'
down_revision: Union[str, None] = '489b626beccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idea_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('readiness', sa.String(length=30), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id', 'version', name='uq_idea_profiles_idea_id_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idea_profiles')
    # ### end Alembic commands ###
