"""add analysis run inputs

Revision ID: b9bbca776d3b
Revises: b2b811ff65c3
Create Date: 2026-09-08 10:38:03.841681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9bbca776d3b'
down_revision: Union[str, None] = 'b2b811ff65c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_run_inputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_run_id', sa.Uuid(), nullable=False),
    sa.Column('input_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['stage_run_id'], ['analysis_stage_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_run_inputs_analysis_run_id'), 'analysis_run_inputs', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_analysis_run_inputs_input_name'), 'analysis_run_inputs', ['input_name'], unique=False)
    op.create_index(op.f('ix_analysis_run_inputs_stage_run_id'), 'analysis_run_inputs', ['stage_run_id'], unique=False)
    op.create_index(op.f('ix_analysis_run_inputs_status'), 'analysis_run_inputs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_run_inputs_status'), table_name='analysis_run_inputs')
    op.drop_index(op.f('ix_analysis_run_inputs_stage_run_id'), table_name='analysis_run_inputs')
    op.drop_index(op.f('ix_analysis_run_inputs_input_name'), table_name='analysis_run_inputs')
    op.drop_index(op.f('ix_analysis_run_inputs_analysis_run_id'), table_name='analysis_run_inputs')
    op.drop_table('analysis_run_inputs')
    # ### end Alembic commands ###
