"""add profile metadata and unknown fields

Revision ID: ed0c43dcae1d
Revises: 80b35165e594
Create Date: 2026-08-13 16:02:23.266500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed0c43dcae1d'
down_revision: Union[str, None] = '80b35165e594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea_profiles', sa.Column('profile_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('idea_profiles', sa.Column('unknown_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idea_profiles', 'unknown_fields')
    op.drop_column('idea_profiles', 'profile_metadata')
    # ### end Alembic commands ###
